server:
  port: 8761

spring:
  application:
    name: eureka-server
  profiles:
    active: dev

management:
  security:
    enabled: false
  health:
    rabbit:
      enabled: false

---
spring:
  profiles: dev
server:
  port: 8761
eureka:
  client:
    # 是否注册到eurekaserver
    registerWithEureka: true
    # 是否拉取信息
    fetchRegistry: false
    # eureka server地址
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # false 关闭自我保护，不管如何都要剔除心跳检测异常的服务
    enableSelfPreservation: false
  instance:
    hostname: eureka1
---
spring:
  profiles: prod
server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${tony.eureka.serviceUrl}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # false 关闭自我保护，不管如何都要剔除心跳检测异常的服务
    enableSelfPreservation: true
    # 服务剔除任务执行周期
    evictionIntervalTimerInMs: 60000
    # 服务端缓存最长时间
    responseCacheUpdateIntervalMs: 30000
  instance:
    hostname: ${HOSTNAME}