server:
  port: 8761

spring:
  application:
    name: eureka-server
  profiles:
    active: dev

management:
  security:
    enabled: false
  health:
    rabbit:
      enabled: false

---
spring:
  profiles: dev

server: 
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    prefer-ip-address: true

---
spring:
  profiles: peer1

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl: 
      defaultZone: http://192.168.1.102:${server.port}/eureka/
  instance:
#    hostname: peer1
    ipAddress: 192.168.1.101
    preferIpAddress: true
#    prefer-ip-address: true  该配置为true表示注册到eureka上的是IP，如果这样的化，eureka服务器就不能通过服务器发现Replicas。
#                             故如果想通过Docker实现eureka高可用，该配置最好使用默认值（false）
#                             此处配置为true且实现高可用也不是没有办法，就是每个eureka服务需映射到Docker环境外，且知道ip。
---
spring:
  profiles: peer2

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.1.101:${server.port}/eureka/
  instance:
#    hostname: peer2
    ipAddress: 192.168.1.102
    preferIpAddress: true
#    prefer-ip-address: true
